name: eas-build
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'ios | android'
        required: true
        default: 'android'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      # ✅ install the app's dependencies inside apps/mobile
      - name: Install deps (mobile)
        working-directory: apps/mobile
        run: npm ci || npm i

      - name: Setup Expo + EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest

      - name: EAS build
        working-directory: apps/mobile
        run: eas build --non-interactive --platform ${{ github.event.inputs.platform }} --profile preview
