name: web
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci (lockfile present)"
            npm ci --no-audit --no-fund
          else
            echo "No package-lock.json => npm install"
            npm install --no-audit --no-fund
          fi

      - name: Ensure web deps (Expo Web + Router)
        env:
          CI: "true"
        run: npx expo install react-dom react-native-web @expo/metro-runtime expo-router

      - name: Verify pdf-lib is installed
        run: node -e "console.log('pdf-lib ->', require.resolve('pdf-lib'))"

      - name: Export static web build
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          EXPO_PUBLIC_DEV_BYPASS_LOGIN: "false"
        run: npx expo export --platform web --output-dir dist

      - name: Patch index.html for GitHub Pages
        working-directory: apps/mobile/dist
        run: |
          node -e "const fs=require('fs');let s=fs.readFileSync('index.html','utf8');s=s.replace(/(src|href)=\"\/_expo/g,'$1=\"./_expo');fs.writeFileSync('index.html',s)"
          cp index.html 404.html
          touch .nojekyll

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: apps/mobile/dist

  deploy-edge:
    runs-on: ubuntu-latest
    env:
      # REQUIRED
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

      # Function runtime secrets (server-side only)
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # OPTIONAL redirect; omit the secret if you don't need it
      INVITE_REDIRECT_TO: ${{ secrets.INVITE_REDIRECT_TO }}
    steps:
      - uses: actions/checkout@v4

      # Install Supabase CLI (official action)
      - uses: supabase/setup-cli@v1
        with:
          version: latest  # pin if you want reproducibility

      - name: Sanity check inputs
        run: |
          set -e
          test -n "$SUPABASE_ACCESS_TOKEN" || (echo "❌ SUPABASE_ACCESS_TOKEN is empty"; exit 1)
          test -n "$SUPABASE_PROJECT_REF"  || (echo "❌ SUPABASE_PROJECT_REF is empty"; exit 1)
          # Verify function exists at expected path
          test -f "supabase/functions/invite-user/index.ts" || (echo "❌ Missing supabase/functions/invite-user/index.ts"; exit 1)
          echo "✅ Inputs look good. Project ref: ${SUPABASE_PROJECT_REF:0:6}…"

      # Set / update runtime secrets used by the function
      - name: Set Supabase function secrets
        run: |
          set -e
          supabase secrets set \
            SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" \
            --project-ref "$SUPABASE_PROJECT_REF"
          # Set INVITE_REDIRECT_TO only when provided
          if [ -n "$INVITE_REDIRECT_TO" ]; then
            supabase secrets set \
              INVITE_REDIRECT_TO="$INVITE_REDIRECT_TO" \
              --project-ref "$SUPABASE_PROJECT_REF"
          fi

      # Deploy the Edge Function and allow browser preflight (OPTIONS) at the platform edge
      - name: Deploy invite-user function
        run: |
          set -e
          supabase functions deploy invite-user \
            --project-ref "$SUPABASE_PROJECT_REF" \
            --no-verify-jwt

      # (Optional) smoke test preflight; does not fail the job
      - name: Smoke test preflight (OPTIONS)
        continue-on-error: true
        run: |
          curl -i -X OPTIONS \
            "https://${SUPABASE_PROJECT_REF}.supabase.co/functions/v1/invite-user" \
            -H "Origin: https://albertoroca96.github.io" \
            -H "Access-Control-Request-Method: POST" \
            -H "Access-Control-Request-Headers: authorization,content-type" || true

      # (Optional) POST smoke test if you provide a valid user access token as a secret
      # Add SUPABASE_TEST_BEARER in repo secrets to enable
      - name: Smoke test POST (requires SUPABASE_TEST_BEARER)
        if: ${{ secrets.SUPABASE_TEST_BEARER != '' }}
        continue-on-error: true
        env:
          SUPABASE_TEST_BEARER: ${{ secrets.SUPABASE_TEST_BEARER }}
        run: |
          curl -i -X POST \
            "https://${SUPABASE_PROJECT_REF}.supabase.co/functions/v1/invite-user" \
            -H "Authorization: Bearer ${SUPABASE_TEST_BEARER}" \
            -H "Content-Type: application/json" \
            --data '{"email":"test+invite@example.com"}' || true

  deploy:
    needs: [build, deploy-edge]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
